app/__init__.py, requirements.txt
Allows for SSL calls to be made from dev stack
=> Update requirements and app init

README.md
Also include some details left out during the setting up of the dev stack
=> Update README with pre-requisites

README.md, requirements.txt
Added some useful information to help with setup
=> Updated README.md to help with setup

app/static/css/style.css, app/templates/views/home.html
Added HTML / CSS to update the contact us section to match designs
=> Updated contact us to match designs

app/static/css/style.css, app/templates/views/home.html
=> Update home page images to fill area

README.md, app/__init__.py, app/config.py, app/gaesession.py, app/main/__init__.py, app/main/views/__init__.py, app/main/views/admin.py, app/templates/views/admin.html, requirements.txt, tests/app/main/views/test_admin.py, tests/app/main/views/test_api.py, tests/conftest.py
Add google auth for admin area
=> Add google auth

app/main/views/index.py, app/static/css/style.css, app/templates/base.html, app/templates/components/footer.html, app/templates/components/header.html, app/templates/views/e-shop.html, app/templates/views/home.html, app/templates/views/resources.html, app/templates/views/what_we_offer.html, app/templates/views/whats_on.html, package-lock.json, tests/app/main/views/test_index.py
Have created individual pages
Header/Footer now have clickable links
Made some small css fixes for Header/Footer
=> Added stubs for all pages

app/static/css/style.css, app/templates/base.html, app/templates/views/home.html, tests/app/main/views/test_index.py
Now uses Bootstrap Carousel over the slick carousel
Has kept the same functionality and displays images the same
This also fixes the resizing of the carousel caption
=> Bootstrap carousel

app/templates/views/home.html
When there are less than 3 events in the future the homepage will break, this will tempoarily stop it from breaking but the design team will need to see whats the best way to proceed
=> Temporary fix for when there are low numbers of future events

app/static/css/style.css, app/templates/components/footer.html, tests/app/main/views/test_index.py
Footer now resizes more neatly, centers when screen is resized
Changed tests to reflect new changes to footer
=> Footer fixes

app/templates/components/footer.html
Added links for instagram and facebook
=> Implement social links

app/static/css/style.css, app/templates/components/footer.html
Privacy policy is now linked to the PDF file and once clicked opens in a new tab
=> Enable privacy policy to open in another tab

app/templates/views/home.html, tests/app/main/views/test_index.py
Test for checking the header appears on the page
Test that checks that a string is being displayed on page for main article which is set to random
Test for that an article is being displayed on the page
=> Added tests for homepage

app/templates/views/admin/events.html
Fix admin events javascript which was not showing the last speaker and also was not showing which dates speakers were allocated to
=> Update admin events to handle event_date speakers better and fix missing speaker

app/clients/__init__.py, app/templates/views/admin/events.html
Also disable publish button to prevent double click
=> Increase timeout to give enough time for api calls to create payment

app/clients/__init__.py, app/config.py, app/main/forms.py
and update requests timeout and booking_code for test
=> Add CSRF to config

app/static/css/style.css, app/templates/components/contact.html, app/templates/views/home.html
Moved this section into a component as it is going to be referenced mutliple times
Images are now scaled the same height
Improved the text styling
=> Fixes for contact us section

app.yaml, app/static/robots.txt, app/templates/base.html
Prevent site being indexed for searching and provide a link to the live website.
=> Stop site indexing

app/clients/api_client.py, app/main/__init__.py, app/main/forms.py, app/main/views/index.py, app/main/views/subscription.py, app/static/css/style.css, app/templates/components/footer.html, app/templates/views/home.html, app/templates/views/subscription.html, tests/app/main/views/admin/test_events.py, tests/app/main/views/test_subscription.py
Subscription form on homepage
Tests for form
=> Subscription form

app/main/decorators.py, app/main/views/index.py, app/main/views/subscription.py, tests/app/main/views/test_subscription.py
Moving subscription for setup to a decorator should make the code in the methods for views clearer
=> Add setup sub form decorator

app/__init__.py, app/clients/api_client.py, app/main/__init__.py, app/main/forms.py, app/main/views/admin/admin.py, app/main/views/admin/emails.py, app/main/views/admin/events.py, app/static/css/admin.css, app/templates/views/admin/admin.html, app/templates/views/admin/emails.html, app/templates/views/admin/events.html, tests/app/main/views/admin/test_emails.py, tests/app/main/views/admin/test_events.py, tests/app/main/views/admin/test_users.py, tests/app/test_errorhandlers.py, tests/conftest.py
Add admin email page and improve events tests
Also refactor code for better routing of admin pages
=> Add admin email

app/main/views/index.py, app/static/css/style.css, app/templates/views/home.html, tests/app/main/views/test_index.py, tests/conftest.py
When there are less than 3 future events the home page breaks because it is expecting at least 3 future events according to the content design.
Displays unique styling based on designs
=> Events cards fully populated

app/templates/views/what_we_offer.html
=> Changed Furhter to further

.travis.yml
Reverts NewAcropolis/frontend#87
=> Revert "wip"

.travis.yml
Reverts NewAcropolis/frontend#91
=> Revert "Update travis script"

app/__init__.py, app/clients/__init__.py, app/main/views/index.py, app/templates/base.html, app/templates/errors/errors.html, app/templates/views/home.html
Still show pages without the api content and report an error.
=> Handle api errors better

app/__init__.py, app/clients/api_client.py, app/main/views/index.py, app/static/css/style.css, app/templates/views/event_details.html, app/templates/views/home.html, app/templates/views/whats_on.html
Can now click on an event which will take you to a new page displaying all event information
*TO BE MERGED AFTER THE EVENTS PAGE*
*MAKE ALL EVENT LINKS WORK*
=> Created event details page

app/templates/views/home.html
Test 
Foundation or Introductory course?
=> Optional - home page

app/templates/views/about.html
=> Text Updates - Siobhan

app/main/forms.py, app/main/views/admin/emails.py
Show all the event dates, not just the first event in events drop down list
Update send_starts_at to 2 weeks before the event
=> Update admin emails

app/templates/views/what_we_offer.html
Have updated all the main text on the courses page, not including the individual synopsis topic text.
=> Courses page main text update - Siobhan

app/static/css/style.css, app/templates/views/what_we_offer.html
Fixed broken styling when introduced new header
=> Fix what we offer styling

app/templates/views/admin/emails.html
Disable user from changing email type and event
Update expiry when start date goes beyond it
=> Fix admin emails html and js

app/templates/views/admin/events.html, app/templates/views/api_test/events.html, app/templates/views/event_details.html, app/templates/views/home.html, app/templates/views/whats_on.html
Use web images for faster page loads
=> Use standard or thumbnail web images

app/templates/views/admin/emails.html
API_BASE_URL shouldn't have a trailing slash, so need  to add  it here
=> Add forward slash to preview link

app/templates/views/admin/emails.html
Adds extra context for users when emails have expired events
=> Add Preview only text for user 

.travis.yml
Reduce pack size as GAE upload limit is 32mb
=> Reduce pack size

app/static/css/style.css, app/templates/components/contact.html, app/templates/components/footer.html, app/templates/components/header.html, app/templates/views/home.html, tests/conftest.py
Includes limit width to 900px, subject to change
Right align nav toggle
Limit text for articles, subject to change
=> Fix homepage style

app/__init__.py, app/config.py, app/static/css/style.css, app/templates/views/courses.html, app/templates/views/events.html, app/templates/views/home.html
Including limiting article text
=> Further improvements to style

app/main/views/__init__.py, app/main/views/courses.py, app/main/views/events.py, app/main/views/index.py, app/static/css/style.css, app/templates/views/courses.html, app/templates/views/event_details.html, main.py, tests/conftest.py
Update course reservation buttons on courses page and event details page.
Also set future events in session and allow a path to unset it for testing.
=> Add course reservation

app/clients/api_client.py, app/main/views/events.py, app/main/views/index.py, tests/app/clients/test_api_client.py, tests/app/main/views/test_api.py, tests/conftest.py
Also do not show future events as being in the past until it is no longer in the future
=> Only show future dates on home page and events

.flake8, app/config.py, app/main/views/admin/events.py, app/templates/views/admin/events.html, tests/app/main/views/admin/test_events.py
Limit upload image size for events to 2mb rather than relying on scaling the image down.
=> Limit upload image size

app.yaml
Reverts NewAcropolis/frontend#279
=> Revert "Always set secure in app.yaml"

app/cache.py, app/clients/api_client.py, app/queue.py
Add cache is_unique, queue backoff_duration and update response to TextProperty
=> Update cache and queue models

app/templates/views/event_details.html
Show donations option without having to create a paypal button
=> Fix donations on event_details

requirements.txt
TypeError: Descriptors cannot not be created directly
=> Set protobug to 3.20.0 to fix error

app/main/views/magazines.py, app/templates/views/magazines.html
Reverts NewAcropolis/frontend#345
=> Revert "Magazine offset"

app/clients/__init__.py, app/clients/api_client.py, app/main/views/api.py, app/queue.py, app/templates/views/admin/queue.html
Also update the admin queue page to show the headers and code to process queued items
=> Update queue model with headers

app/config.py, app/queue.py
Purge error and suspend after 14 days rather than 7 days
=> Update queue purge to delete error and suspend

app/static/css/email-copy.css, app/static/js/email-copy.js, app/templates/views/admin/orders.html
Add email copy function from github.com/aimeeinfo/copy-email-address-links-to-clipboard.markdown
=> Add email_address and email-copy functions

app/clients/api_client.py
Log the error and do not add it to the cache list
=> Handle error from cache update

app/main/views/shop.py
Reverts NewAcropolis/frontend#490
=> Revert "Use paypal account ID"

app/config.py
Reverts NewAcropolis/frontend#491
=> Revert "Set delivery to UK to 1p for testing"
